baseURL = "https://hzh.moe/"
languageCode = "zh-cn"
title = "Notes"
theme = "minimal"

[params]
  author = "Zhiheng"
  description = "Just some notes..."
  githubUsername = "walktall"
  accent = "red"
  showBorder = true
  backgroundColor = "white"
  font = "Open Sans"
  favicon = "favicon.ico"
  highlight = true
  highlightStyle = "atom-one-dark"
  highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
  url = "/"
  name = "Home"
  weight = 1

[[menu.main]]
  url = "/posts/"
  name = "Posts"
  weight = 2

[[menu.main]]
  url = "/about/"
  name = "About"
  weight = 3

[[menu.icon]]
    url = "mailto:zh-@outlook.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/walktall/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/ObserverDaemon/"
    name = "twitter"
    weight = 3
